{
 "title": "benchmark-stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU  使用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"victoria-benchmark-prometheus.*|victoria-benchmark-victor.*\"}[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "内存使用",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"victoria-benchmark-victoria-metrics-1|victoria-benchmark-prometheus.*\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "磁盘占用",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"host-node-0:9100\",mountpoint=~\"/prometheus|/victoria.*\"}- node_filesystem_free_bytes{instance=\"host-node-0:9100\",mountpoint=~\"/prometheus|/victoria.*\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}