version: '3.3'
services:
  prometheus: 
    image: prom/prometheus:main
    restart: always
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --enable-feature=otlp-write-receiver
    volumes:
      - prometheus-data:/prometheus
  
  otlp-example:
    image: songjiayang/otlp-example:0.0.1
    depends_on:
      - prometheus
    ports:
      - "8080:8080"

volumes:
  prometheus-data:

