version: '3.3'
services:
  prometheus: 
    image: prom/prometheus:main
    restart: always
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
    volumes:
      - prometheus-data:/prometheus
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/hosts:/etc/hosts
    depends_on:
      - node-exporter
    networks:
      - default

  node-exporter: 
    image: prom/node-exporter:v1.6.1
    restart: always
    ports:
      - "9100:9100"
    networks:
      default:
        ipv4_address: 10.5.0.2

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.92.1
    ports:
      - "8428:8428"
    volumes:
      - victoria-metrics-data:/path/to/victoria-metrics-data
    depends_on:
      - node-exporter
    networks:
      - default

volumes:
  prometheus-data:
  victoria-metrics-data:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

